# netlify.toml (repo root)

[build]
  # the single command—no base directory needed
  command   = "npm --prefix basebridge-ui install && npm --prefix basebridge-ui run build"
  publish   = "basebridge-ui/build"
  functions = "basebridge-ui/netlify/functions"

# (we handle redirects in public/_redirects)
