# netlify.toml
[build]
  publish   = "build"                # your CRA production build
  functions = "netlify/functions"    # where we’ll put our Lambda

[[redirects]]
  from     = "/*"
  to       = "/index.html"
  status   = 200
